### ISSUE TITLE
Missing required header 'X-yanagishima-datasources'

### ISSUE THREAD

**Issue by roeeshachar** [wyukawa/yanagishima#16]
Hi,

Looks awesome! but for some reason I can get it to run.
For my reasons I didn't enclose the host and port, but it is working in a different framework.

I described the issue below.

Thanks!
Roee

**yanagishima version**: 3.0

**presto version**:  couldn't find how to check

**conf/yanagishima.properties**:

jetty.port=8080
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=presto1
presto.coordinator.server.presto1=WORKING_HOST:PORT
presto.redirect.server.presto1=WORKING_HOST:PORT
catalog.presto1=hive
schema.presto1=default
schema.presto1=default
select.limit=500
audit.http.header.name=some.auth.header

**JVM version** (`java -version`):

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Server OS version** (`uname -a` if on a Unix-like system):
Linux  3.19.0-74-generic #82~14.04.1-Ubuntu SMP Fri Oct 21 15:43:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**
localhost

**Browser**:
chromium
**Description of the problem including expected versus actual behavior**:

when opening main page, 
which for some reason is "http://localhost:8080/#datasource=&tab="
with missing parameters

there is an error call to /datasource
with the following message: 

HTTP ERROR: 500

Problem accessing /datasource. Reason:

    java.lang.RuntimeException: Missing required header 'X-yanagishima-datasources'.

**Steps to reproduce**:

 1. go to main page
 2. see /datasource
 3.

**Provide logs (if relevant)**:
	
[log.txt](https://github.com/wyukawa/yanagishima/files/1022842/log.txt)

**Provide screenshots (if relevant)**:

**Comment by wyukawa** [comment]
Now, please use binary(https://bintray.com/artifact/download/wyukawa/generic/yanagishima-3.0.zip) 
or 3.0 tag instead of building source code. 

Although yanagishima has a authorization feature, reverse proxy and some manual procedures are necessary. So I tune off it in version 3 tag. 
But in master branch, authorization feature is on because we use it. 

And yanagishima UI and backend API development is separated in our environment and it's not synchronized to push to github.com 

As a conclusion, currently, I don't recommend to use master branch.

**Comment by roeeshachar** [comment]
Hey!

Worked like a charm, thanks!
Fast and smartly designed!

Before I opened the issue, at first I tried to download the version you stated, but it was unresponsive for some reason.
Now it's all good! :)
